### ISSUE TITLE
Error in unserialize(mSetObj) : read error

### ISSUE THREAD

**Issue by whitedayrat** [xia-lab/MetaboAnalystR#222] opened 2022-02-23 06:01 UTC
When I run this code:

mSet<-PlotKEGGPath(mSet, "Glycine, serine and threonine metabolism",528, 480, "png", NULL)

I got this Error:

Error in unserialize(mSetObj) : read error

How can I solve this issue?

Thanks.

> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

**Comment by ChangLu92** [comment] 2022-03-07 14:15
I have the same problem. I tried to debug it and found the problem is from the sentence 'mSetObj <- httr::content(request, "raw")', since the 'mSetObj' is empty after this sentence. It will be nice if you can have a look at what when wrong. Thanks.

**Comment by Chen-kuan** [comment] 2022-05-03 04:40
这里就是爬虫爬不到东西，我偶尔也能爬到东西，但是是随机的，希望有懂爬虫的把代码改一下；或许，是服务器端有问题，那我们就没办法画图。

**Comment by Zhiqiang-PANG** [comment] 2022-11-05 19:37
I am closing this, if you can provide a reproducile example, please post it here: https://omicsforum.ca/c/metaboanalyst/5

**Closed by Zhiqiang-PANG** 2022-11-05 19:37 UTC

**Comment by Michelle822** [comment] 2023-01-27 11:33
> When I run this code:
> 
> mSet<-PlotKEGGPath(mSet, "Glycine, serine and threonine metabolism",528, 480, "png", NULL)
> 
> I got this Error:
> 
> Error in unserialize(mSetObj) : read error
> 
> How can I solve this issue?
> 
> Thanks.
> 
> > sessionInfo()
> > R version 4.1.2 (2021-11-01)
> > Platform: x86_64-w64-mingw32/x64 (64-bit)
> > Running under: Windows 10 x64 (build 19044)

Hello, Did you find a solution for this problem? Thanks a lot!

**Comment by MyNameAmir** [comment] 2023-02-02 18:20
Error in unserialize(httr::content(request, "raw")) : read error

Similar issue here and I have posted on Omicsforum also, any help would be greatly appreciated thanks!!

 version  R version 4.2.2 (2022-10-31)
 os       macOS Ventura 13.1
 system   x86_64, darwin17.0
 ui       RStudio

**Comment by CM-07** [comment] 2023-07-14 19:21
@MyNameAmir Did you find a solution to the problem? I have the same problem.

**Comment by howtofindme** [comment] 2023-07-19 11:04
same problem,here is the codes :

![image](https://github.com/xia-lab/MetaboAnalystR/assets/72066151/421f7f6b-bf0c-41f5-8c13-1c6a86f2e281)

**Comment by howtofindme** [comment] 2023-07-19 11:06
> I am closing this, if you can provide a reproducile example, please post it here: https://omicsforum.ca/c/metaboanalyst/5

here is the error :
![image](https://github.com/xia-lab/MetaboAnalystR/assets/72066151/9de9db63-bb8e-4be7-96a2-1aa75ddca2c9)

**Comment by howtofindme** [comment] 2023-07-19 11:12
> When I run this code:
> 
> mSet<-PlotKEGGPath(mSet, "Glycine, serine and threonine metabolism",528, 480, "png", NULL)
> 
> I got this Error:
> 
> Error in unserialize(mSetObj) : read error
> 
> How can I solve this issue?
> 
> Thanks.
> 
> > sessionInfo()
> > R version 4.1.2 (2021-11-01)
> > Platform: x86_64-w64-mingw32/x64 (64-bit)
> > Running under: Windows 10 x64 (build 19044)

hi ,have you solved it?
 this is my error same as you 👍 
![image](https://github.com/xia-lab/MetaboAnalystR/assets/72066151/0632fcc6-26bc-4721-b564-292adbc1060d)
