### ISSUE TITLE
PLSDA warning messages

### ISSUE THREAD

**Issue by sstandage** [xia-lab/MetaboAnalystR#49] opened 2019-06-18 16:00 UTC
When I run PLSDA functions in MetaboAnalystR I get the following errors:

> mSet<-PLSDA.CV(mSet, "T",5, "Q2")
Warning message:
In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :
  There were missing values in resampled performance measures.
> mSet<-PlotPLS.Imp(mSet, "Serum_VIP_", "png", 300, width=NA, "vip", "Comp. 1", 15,FALSE)
Warning message:
In RColorBrewer::brewer.pal(25, colorpalette) :
  n too large, allowed maximum for palette RdYlGn is 11
Returning the palette you asked for with that many colors

The functions still generate results and build a figure, but I am uncertain of the integrity of the computation. Did something go wrong that I need to change?

Thanks!

**Comment by jessica-ewald** [comment] 2022-11-05 19:47
This has been addressed in version 4.0, which will be released soon. 

The issue is with RColorBrewer, which only affects visualizing the results. Any calculated stats are unaffected.

**Closed by jessica-ewald** 2022-11-05 19:47 UTC

**Comment by sstandage** [comment] 2022-11-07 11:40
Thank you. I'll look forward to it.
