### ISSUE TITLE
Problem in the calculation of low and high of the features in function PlotImpVars under frequency measure

### ISSUE THREAD

**Issue by rqhu1995** [xia-lab/MetaboAnalystR#234] opened 2022-07-27 10:19 UTC
When calculating the "low/high" of each feature in the function `PlotImpVars` under frequency measurement mode using

`PlotImpVars(mSet, "cls_imp_1_", "png", 72, <different model index>, "freq", 15)`

(starting from line 1783 in file `biomarker_utils.R`)

I noticed that choosing different models would generate different high/low result **on a same feature**. Theoretically, this should not be possible since high/low for a feature is calculated by comparing the median of values the two classes on the normalized dataset. Therefore, it only depends on the normalized dataset. 

Then I dug into the source in function `PlotImpVars`, and traced that the value of variable `lowhigh`. 

```r
  mds <- apply(data, 2,
               function(x){
                 tapply(x, cls, median);
               });
  
  lowhigh <- apply(mds, 2,
                   function(x){
                     ifelse(rank(x)==1, "Low", "High")
                   });
  lowhigh <- t(lowhigh);
```

Up to here, the value of `lowhigh` is as expected. However, I found then the code seems to cover the feature name using `names(imp.vec)`. However, using `View(lowhigh)` in RStudio, I can see the row names of every `lowhigh`, and the sequence of `names(imp.vec)` is not corresponding to the table of `lowhigh` I saw in RStudio. (Sorry, not familiar with R)

```r
  rownames(lowhigh) <- names(imp.vec);
  colnames(lowhigh) <- levels(cls);
  mSetObj$analSet$multiROC$lowhigh <- lowhigh;
```

I think here the name are wrongly assigned to `lowhigh`, and that caused the problem.

Actually, I also notice that in the model other than `freq`, the `imp.vec` is sorted while in `freq` is isn't.

```r
  if(measure=="freq"){
    imp.vec <- imp.mat[,1];
    xlbl <- "Selected Frequency (%)";
  }else{ # default sort by freq, need to reorder
    imp.vec <- sort(imp.mat[,2], decreasing=T);
    xlbl <- "Average Importance";
  }
```

I am not sure whether here in `freq` measurement it should be similarly sorted by `imp.vec <- sort(imp.mat[,1], decreasing=T)`.

**Comment by xia-lab** [comment] 2022-11-05 20:32
The issue is fixed in our web platform, and will be available in MetaboAnalystR 4.0 to be release soon

**Closed by xia-lab** 2022-11-05 20:32 UTC
